name: Build and Test

on:
  push:
    branches: [ "dev/**" ]
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@juice-js'
      - run: npm ci
      - run: npm run build @juice-js/core --if-present
      - run: npm run build @juice-js/localize --if-present
      - run: npm run build @juice-js/layout --if-present
      - run: npm run build @juice-js/auth --if-present
      - run: npm run build @juice-js/tenant --if-present
      - run: npm test -- --watch=false --browsers=ChromeHeadless
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
